
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: opl
      POSTGRES_PASSWORD: opl
      POSTGRES_DB: opl
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U opl -d opl"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file: apps/web/.env.local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: sh -c "npx prisma db push && node scripts/seed.cjs && node scripts/setup-views.cjs && npx next dev -p 3000"




volumes:
  db: {}
